return function(H)
    local config = Package.Require("games/duel/data/config.lua")
    local Duel = Package.Require("games/duel/logic.lua")(config)

    -- Un 1v1 plein et lance : A camp 1, B camp 2.
    local function duel_lance()
        local d = Duel.Nouveau()
        Duel.Entrer(d, "A"); Duel.Entrer(d, "B")
        Duel.Pret(d, "A", true); Duel.Pret(d, "B", true)
        Duel.Lancer(d); Duel.DebutManche(d)
        return d
    end

    H.describe("games/duel/logic", function()

        H.it("le premier arrive cree le duel et les camps s'alternent", function()
            local d = Duel.Nouveau()
            H.assert_true(Duel.Entrer(d, "A"), "A entre")
            H.assert_eq(d.createur, "A", "createur")
            H.assert_eq(d.phase, "attente", "attente")
            Duel.Entrer(d, "B")
            H.assert_eq(d.joueurs.A.camp, 1, "A camp 1")
            H.assert_eq(d.joueurs.B.camp, 2, "B camp 2")
            Duel.Entrer(d, "C"); Duel.Entrer(d, "D")
            local ok, raison = Duel.Entrer(d, "E")
            H.assert_false(ok, "quatre au plus")
            H.assert_eq(raison, "complet", "raison")
        end)

        H.it("seul le createur choisit la mise, parmi les paliers", function()
            local d = Duel.Nouveau()
            Duel.Entrer(d, "A"); Duel.Entrer(d, "B")
            H.assert_false(Duel.ChoisirMise(d, "B", 50), "B ne choisit pas")
            H.assert_false(Duel.ChoisirMise(d, "A", 42), "mise hors palier")
            Duel.Pret(d, "B", true)
            H.assert_true(Duel.ChoisirMise(d, "A", 100), "mise a 100")
            H.assert_false(d.joueurs.B.pret, "changer la mise remet pas pret")
        end)

        H.it("le format suit le nombre de joueurs, un impair attend", function()
            local d = Duel.Nouveau()
            Duel.Entrer(d, "A"); Duel.Entrer(d, "B"); Duel.Entrer(d, "C")
            for _, id in ipairs({ "A", "B", "C" }) do Duel.Pret(d, id, true) end
            H.assert_eq(Duel.FormatAttendu(d), 2, "trois joueurs : on attend un 2v2")
            H.assert_false(Duel.ToutPret(d), "trois ne partent pas")
            Duel.Quitter(d, "C")
            H.assert_true(Duel.ToutPret(d), "a deux, 1v1")
            Duel.Lancer(d)
            H.assert_eq(d.format, 1, "1v1")
        end)

        H.it("ne part que plein et tout le monde pret", function()
            local d = Duel.Nouveau()
            Duel.Entrer(d, "A"); Duel.Pret(d, "A", true)
            H.assert_false(Duel.ToutPret(d), "il manque un joueur")
            Duel.Entrer(d, "B")
            H.assert_false(Duel.ToutPret(d), "B pas pret")
            Duel.Pret(d, "B", true)
            H.assert_true(Duel.ToutPret(d), "pret")
        end)

        H.it("le createur qui part passe la main, le dernier vide l'arene", function()
            local d = Duel.Nouveau()
            Duel.Entrer(d, "A"); Duel.Entrer(d, "B")
            Duel.Quitter(d, "A")
            H.assert_eq(d.createur, "B", "B createur")
            Duel.Quitter(d, "B")
            H.assert_eq(d.phase, "vide", "arene vide")
        end)

        H.it("on ne touche ni son camp, ni un mort, ni hors combat", function()
            local d = Duel.Nouveau()
            Duel.Entrer(d, "A"); Duel.Entrer(d, "B"); Duel.Entrer(d, "C")
            H.assert_false(Duel.PeutToucher(d, "A", "B"), "pas en combat")
        end)

        H.it("premier a deux manches", function()
            local d = duel_lance()
            H.assert_true(Duel.PeutToucher(d, "A", "B"), "A peut toucher B")
            local r = Duel.Mort(d, "B")
            H.assert_true(r.manche, "manche jouee")
            H.assert_eq(r.gagnant, 1, "camp 1")
            H.assert_eq(d.phase, "entre_manches", "pause")
            Duel.DebutManche(d)
            H.assert_true(d.joueurs.B.vivant, "B revit")
            r = Duel.Mort(d, "B")
            H.assert_true(r.fin, "duel fini")
            H.assert_eq(r.gagnant, 1, "A gagne")
            H.assert_eq(d.phase, "fin", "fin")
        end)

        H.it("abandonner en combat donne la victoire a l'autre camp", function()
            local d = duel_lance()
            local r = Duel.Quitter(d, "A")
            H.assert_true(r and r.fin, "fin")
            H.assert_eq(r.gagnant, 2, "B gagne")
        end)

        H.it("en 2v2, une manche ne tombe que quand tout le camp est mort", function()
            local d = Duel.Nouveau()
            Duel.Entrer(d, "A"); Duel.Entrer(d, "B"); Duel.Entrer(d, "C"); Duel.Entrer(d, "D")
            for _, id in ipairs({ "A", "B", "C", "D" }) do Duel.Pret(d, id, true) end
            H.assert_true(Duel.ToutPret(d), "pret")
            Duel.Lancer(d); Duel.DebutManche(d)
            H.assert_eq(d.format, 2, "2v2")
            H.assert_nil(Duel.Mort(d, "B"), "B mort, D encore debout")
            local r = Duel.Mort(d, "D")
            H.assert_eq(r and r.gagnant, 1, "camp 1 prend la manche")
        end)

        H.it("abandonner entre deux manches ne marque pas de point mais peut finir", function()
            local d = Duel.Nouveau()
            Duel.Entrer(d, "A"); Duel.Entrer(d, "B"); Duel.Entrer(d, "C"); Duel.Entrer(d, "D")
            for _, id in ipairs({ "A", "B", "C", "D" }) do Duel.Pret(d, id, true) end
            Duel.Lancer(d); Duel.DebutManche(d)
            Duel.Mort(d, "B"); Duel.Mort(d, "D")       -- 1-0 pour le camp 1
            H.assert_nil(Duel.Quitter(d, "C"), "C part, A reste : pas de fin")
            H.assert_eq(d.scores[1], 1, "score inchange")
            Duel.DebutManche(d)
            H.assert_false(d.joueurs.C.vivant, "un parti ne revit pas")
        end)
    end)
end
