return function(H)
    local config = Package.Require("games/liars_bar/data/config.lua")
    local Salon = Package.Require("games/liars_bar/salon.lua")(config)

    local function assis(...)
        local out = {}
        for i, p in ipairs({ ... }) do
            out[i] = { chair = p[1], nom = p[2], bot = p[3] or nil }
        end
        return out
    end

    H.describe("games/liars_bar/salon", function()

        H.it("le premier humain assis choisit la mise ; les bots sont prets d'office", function()
            local s = Salon.New()
            local a = assis({ 3, "Bot 3", true }, { 2, "Ana" }, { 4, "Ben" })
            Salon.Accorder(s, a)
            H.assert_eq(s.createur, 2, "Ana, premier humain")
            H.assert_true(s.pret[3], "le bot est pret")
            H.assert_false(Salon.ChoisirMise(s, a, 4, 50), "Ben ne choisit pas")
            H.assert_false(Salon.ChoisirMise(s, a, 2, 42), "hors palier")
            H.assert_true(Salon.ChoisirMise(s, a, 2, 100), "Ana choisit 100")
            H.assert_eq(s.mise, 100, "mise")
        end)

        H.it("changer la mise remet les humains en pas pret, pas les bots", function()
            local s = Salon.New()
            local a = assis({ 1, "Ana" }, { 2, "Ben" }, { 3, "Bot", true })
            Salon.Accorder(s, a)
            Salon.Pret(s, a, 2, true)
            Salon.ChoisirMise(s, a, 1, 50)
            H.assert_false(s.pret[2] == true, "Ben doit accepter la nouvelle mise")
            H.assert_true(s.pret[3], "le bot reste pret")
        end)

        H.it("part quand tous les assis sont prets et assez nombreux", function()
            local s = Salon.New()
            local a = assis({ 1, "Ana" }, { 2, "Ben" })
            Salon.Accorder(s, a)
            Salon.Pret(s, a, 1, true); Salon.Pret(s, a, 2, true)
            H.assert_false(Salon.ToutPret(s, a), "deux, c'est trop peu")
            a = assis({ 1, "Ana" }, { 2, "Ben" }, { 3, "Bot", true })
            Salon.Accorder(s, a)
            H.assert_true(Salon.ToutPret(s, a), "trois prets")
            Salon.Pret(s, a, 2, false)
            H.assert_false(Salon.ToutPret(s, a), "Ben se retire")
        end)

        H.it("des bots seuls ne lancent rien", function()
            local s = Salon.New()
            local a = assis({ 1, "B1", true }, { 2, "B2", true }, { 3, "B3", true })
            Salon.Accorder(s, a)
            H.assert_false(Salon.ToutPret(s, a), "aucun humain")
        end)

        H.it("le createur qui part passe la main ; sans humain la mise revient au premier palier", function()
            local s = Salon.New()
            local a = assis({ 1, "Ana" }, { 4, "Ben" })
            Salon.Accorder(s, a)
            Salon.ChoisirMise(s, a, 1, 250)
            Salon.Pret(s, a, 1, true)
            a = assis({ 4, "Ben" })
            Salon.Accorder(s, a)
            H.assert_eq(s.createur, 4, "Ben reprend")
            H.assert_eq(s.pret[1], nil, "Ana oubliee")
            H.assert_eq(s.mise, 250, "la mise reste")
            Salon.Accorder(s, {})
            H.assert_eq(s.mise, config.paliers[1], "salon vide")
        end)

        H.it("la vue montre chaque chaise et une mise nulle avec des bots", function()
            local s = Salon.New()
            local a = assis({ 2, "Ana" }, { 3, "Bot", true })
            Salon.Accorder(s, a)
            Salon.ChoisirMise(s, a, 2, 100)
            local v = Salon.Vue(s, a)
            H.assert_eq(#v.places, config.max_seats, "une ligne par chaise")
            H.assert_true(v.places[1].vide, "chaise 1 libre")
            H.assert_eq(v.places[2].nom, "Ana", "Ana chaise 2")
            H.assert_eq(v.mise, 0, "avec un bot, rien en jeu")
            H.assert_true(v.avec_bots, "avec bots")
        end)
    end)
end
