return function(H, Stubs)
    local SharedConfig = Package.Require("Shared/config.lua")
    local Journal      = Package.Require("liars_bar/journal.lua")(SharedConfig.liars_hud)

    local function derniere(j) return j.lines[#j.lines] end

    -- Une table ou je suis a la chaise 1, avec Bot 2, et c'est mon tour.
    local function table_a_moi(main)
        local j = Journal.New()
        j:On("seated", 1, "zix", true)
        j:On("seated", 2, "Bot 2", false)
        j:On("started", { { chair = 1, name = "zix" }, { chair = 2, name = "Bot 2" } })
        j:On("deal", main or { "king", "queen", "ace", "joker", "king" })
        j:On("turn", 1)
        return j
    end

    H.describe("liars_bar/journal", function()
        H.it("reconnait sa chaise et nomme les joueurs", function()
            local j = Journal.New()
            j:On("seated", 1, "zix", true)
            j:On("seated", 2, "Bot 2", false)
            H.assert_eq(j.my_chair, 1, "ma chaise")
            H.assert_eq(derniere(j).text, "Bot 2 s'assoit, chaise 2", "ligne")
        end)

        H.it("annonce le lancement puis la carte de table", function()
            local j = table_a_moi()
            j:On("table_card", "queen")
            H.assert_eq(j.table_rank, "queen", "carte de table")
            H.assert_eq(derniere(j).text, "Carte de table : Dame", "ligne")
        end)

        H.it("dit quand c'est mon tour", function()
            local j = table_a_moi()
            H.assert_true(j:IsMyTurn(), "mon tour")
            H.assert_eq(derniere(j).text, "Tour : à toi !", "ligne")
        end)

        H.it("refuse la selection hors de son tour", function()
            local j = table_a_moi()
            j:On("turn", 2)
            H.assert_false(j:Toggle(1), "selection")
            H.assert_eq(derniere(j).text, "Tour : Bot 2 (chaise 2)", "ligne")
        end)

        H.it("plafonne la selection a trois cartes", function()
            local j = table_a_moi()
            H.assert_true(j:Toggle(1), "1")
            H.assert_true(j:Toggle(2), "2")
            H.assert_true(j:Toggle(3), "3")
            H.assert_false(j:Toggle(4), "4")
            H.assert_eq(table.concat(j:Selection(), ","), "1,2,3", "selection")
        end)

        H.it("refuse un indice hors de la main", function()
            local j = table_a_moi({ "king", "ace" })
            H.assert_false(j:Toggle(3), "indice 3")
        end)

        H.it("retire les cartes posees a la confirmation", function()
            local j = table_a_moi()
            j:Toggle(2)
            j:Toggle(4)
            j:MarkPending(j:Selection())
            j:On("cards_played", 1, 2)
            H.assert_eq(table.concat(j.hand, ","), "king,ace,king", "main")
            H.assert_eq(derniere(j).text, "zix (chaise 1) pose 2 carte(s)", "ligne")
        end)

        H.it("une pose refusee laisse la main intacte", function()
            local j = table_a_moi()
            j:Toggle(1)
            j:MarkPending(j:Selection())
            j:On("intent_result", "liars_play", false, { audit = "pas son tour" })
            j:On("cards_played", 1, 1)
            H.assert_eq(#j.hand, 5, "main")
            H.assert_eq(j.lines[#j.lines - 1].kind, "refus", "type de ligne")
            H.assert_eq(j.lines[#j.lines - 1].text, "Refusé : pas son tour", "texte")
        end)

        H.it("traduit un refus avec son contexte", function()
            local j = Journal.New()
            j:On("refused", "pas_assez_de_joueurs", { assis = 1, minimum = 3 })
            H.assert_eq(derniere(j).text, "Refusé : pas assez de joueurs (1/3)", "texte")
            H.assert_eq(derniere(j).kind, "refus", "type")
        end)

        H.it("un spectateur suit la table sans main", function()
            local j = Journal.New()
            j:On("seated", 1, "zix", false)
            j:On("started", { { chair = 1, name = "zix" } })
            j:On("turn", 1)
            H.assert_nil(j.my_chair, "chaise")
            H.assert_eq(#j.hand, 0, "main")
            H.assert_false(j:IsMyTurn(), "tour")
        end)

        H.it("raconte l'accusation et le tir", function()
            local j = table_a_moi()
            j:On("accuse", 2, 1)
            H.assert_eq(derniere(j).text, "Bot 2 (chaise 2) accuse zix (chaise 1)", "accusation")
            j:On("reveal", 1, { "king", "joker" })
            H.assert_eq(derniere(j).text, "Révélé chez zix (chaise 1) : Roi, Joker", "revelation")
            j:On("designated", 1)
            H.assert_eq(derniere(j).text, "Tu dois tirer : E sur le revolver", "designation")
            j:On("shoot", 1, 3, false)
            H.assert_eq(derniere(j).text,
                "zix (chaise 1) tire… à blanc (tir 3 sur 6, prochain : 1 chance sur 3)", "tir")
        end)

        H.it("garde les dernieres lignes seulement", function()
            local j = Journal.New()
            for i = 1, 12 do j:On("refused", "code_" .. i) end
            H.assert_eq(#j.lines, 8, "nombre")
            H.assert_eq(derniere(j).text, "Refusé : code_12", "derniere")
        end)

        H.it("place le curseur sur la premiere carte a la donne", function()
            local j = table_a_moi()
            H.assert_eq(j.cursor, 1, "curseur")
        end)

        H.it("la molette fait tourner le curseur dans la main", function()
            local j = table_a_moi()
            j:MoveCursor(1)
            H.assert_eq(j.cursor, 2, "avance")
            j:MoveCursor(-2)
            H.assert_eq(j.cursor, 5, "revient par la fin")
        end)

        H.it("le clic choisit la carte sous le curseur", function()
            local j = table_a_moi()
            j:MoveCursor(2)
            H.assert_true(j:ToggleCursor(), "choisie")
            H.assert_eq(table.concat(j:Selection(), ","), "3", "selection")
        end)

        H.it("le curseur reste dans la main apres une pose", function()
            local j = table_a_moi()
            j:MoveCursor(-1)
            j:Toggle(4)
            j:Toggle(5)
            j:MarkPending(j:Selection())
            j:On("cards_played", 1, 2)
            H.assert_eq(j.cursor, 3, "curseur borne")
        end)

        H.it("compte les cartes de chaque chaise", function()
            local j = table_a_moi()
            j:On("table_card", "king")
            H.assert_eq(j.counts[2], 5, "cinq cartes a la donne")
            j:On("cards_played", 2, 3)
            H.assert_eq(j.counts[2], 2, "moins la pose")
            j:On("eliminated", 2)
            H.assert_eq(j.counts[2], 0, "elimine")
            j:On("table_card", "queen")
            H.assert_eq(j.counts[2], 0, "un elimine ne recoit plus rien")
        end)

        H.it("tient le tas du centre et la revelation", function()
            local j = table_a_moi()
            j:On("table_card", "king")
            j:On("cards_played", 2, 3)
            j:On("cards_played", 1, 1)
            H.assert_eq(#j.pile, 2, "deux poses")
            H.assert_eq(j.pile[1].count, 3, "premiere pose")
            j:On("reveal", 1, { "king" })
            H.assert_eq(j.revealed.chair, 1, "revelee")
            j:On("table_card", "queen")
            H.assert_eq(#j.pile, 0, "tas vide a la nouvelle manche")
            H.assert_nil(j.revealed, "plus de revelation")
        end)

        H.it("change de version a chaque modification", function()
            local j = Journal.New()
            local v = j.version
            j:On("seated", 1, "zix", true)
            H.assert_true(j.version > v, "evenement")
            v = j.version
            j:MoveCursor(1)
            H.assert_true(j.version > v, "curseur")
        end)

        H.it("compte les tirs du revolver", function()
            local j = table_a_moi()
            j:On("shoot", 2, 1, false)
            H.assert_eq(derniere(j).text,
                "Bot 2 (chaise 2) tire… à blanc (tir 1 sur 6, prochain : 1 chance sur 5)", "tir 1")
            j:On("shoot", 2, 5, false)
            H.assert_eq(derniere(j).text,
                "Bot 2 (chaise 2) tire… à blanc (tir 5 sur 6, le prochain est mortel)", "tir 5")
            j:On("shoot", 2, 3, true)
            H.assert_eq(derniere(j).text, "Bot 2 (chaise 2) tire… BANG (tir 3 sur 6)", "mortel")
        end)

        H.it("donne la raison de la fin de manche", function()
            local j = Journal.New()
            j:On("round_ended", "challenged")
            H.assert_eq(derniere(j).text, "Fin de manche : l'accusation est réglée", "contestation")
            j:On("round_ended", "exhausted")
            H.assert_eq(derniere(j).text,
                "Manche nulle : plus personne pour répondre à la dernière pose", "nulle")
        end)

        H.it("la fin de partie vide la main", function()
            local j = table_a_moi()
            j:On("match_ended", 2)
            H.assert_eq(#j.hand, 0, "main")
            H.assert_eq(derniere(j).text, "Victoire : Bot 2 (chaise 2)", "ligne")
        end)
    end)
end
